name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: echo "No tests yet"

      - name: Construir Docker
        run: docker build -t mi-app .

      - name: Ejecutar contenedor
        run: docker run -d -p 3000:3000 mi-app

      - name: Probar app
        run: curl --retry 5 --retry-delay 5 http://localhost:3000