name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - run: echo "No tests yet"

      - run: docker build -t mi-app .

      - run: docker run -d -p 3000:3000 mi-app

      - run: sleep 5

      - run: curl --retry 5 --retry-delay 5 http://localhost:3000